---

- name: Mail | Setup Mail Alerts
  template:
    src: mail.j2
    dest: "{{ monit_includes }}/mail"
    owner: "{{ monit_owner }}"
    group: "{{ monit_group }}"
    mode: 0660
  notify:
    - restart macos monit
    - restart debian monit
  when: monit_mail_enabled
