---

- name: Main | Register Monit's Executable Location
  shell: 'command -v monit' # noqa 305
  register: _monit_executable
  ignore_errors: yes
  changed_when: false

- name: Setting Monit's Executable Location
  set_fact:
    monit_executable: "{{ _monit_executable.stdout }}"
  when: _monit_executable is succeeded

- name: Setting Monit's Executable Location | Default
  set_fact:
    monit_executable: "{{ default_monit_executable }}"
  when: _monit_executable is failed

- include_vars: debian.yml
  when:  ansible_os_family == "Debian"

- include_vars: redhat.yml
  when: ansible_os_family == "RedHat"

- include_vars: macOS.yml
  when: ansible_os_family == "Darwin"

- import_tasks: autostart.yml
  tags: monit_autostart
  become: true

- import_tasks: config.yml
  tags: monit_config
  become: true

- import_tasks: monitors.yml
  tags: monit_monitors
  become: true
